
# The name of the workflow execution
name: Order Large Cheese Pizza

# Event we will be listening for
on: [issue_comment]

jobs:

  # Places an order
  order_alex:

    # Will run on linux
    runs-on: macos-latest
    
    # Checking the comment body for our trigger phrase
    # If found in the body, the steps below will run
    if: (contains(github.event.comment.body,'/order pizza Alexandria'))

    # The procedural functionality of the place_order job
    steps:
    - uses: actions/checkout@v2
    
    #Build Project
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    #Order Pizza
    - name: Order Pizza
      uses: hollywood/its-pizza-time@main
      with:
        RECEIVING_ADDRESS: ${{ secrets.ALEXANDRIA_ADDRESS }}
        CC_NUMBER: ${{ secrets.CC_NUMBER }}
        CC_EXP: ${{ secrets.CC_EXP }}
        CC_CVV: ${{ secrets.CC_CVV }}
        CC_ZIP: ${{ secrets.CC_ZIP }}
      env:
        LOG_LEVEL: debug


  order_munich:
    runs-on: macos-latest
    if: (contains(github.event.comment.body,'/order pizza Munich'))

    # The procedural functionality of the place_order job
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Order Pizza
      uses: hollywood/its-pizza-time@main
      with:
        RECEIVING_ADDRESS: ${{ secrets.MUNICH_ADDRESS }}
        CC_NUMBER: ${{ secrets.CC_NUMBER }}
        CC_EXP: ${{ secrets.CC_EXP }}
        CC_CVV: ${{ secrets.CC_CVV }}
        CC_ZIP: ${{ secrets.CC_ZIP }}
      env:
        LOG_LEVEL: debug
