
# The name of the workflow execution
name: Order Large Cheese Pizza

# Event we will be listening for
on: [issue_comment]

# Entry point to our workflow jobs
jobs:

  # Places an order
  place_order:

    # Will run on linux
    runs-on: macos-latest
    
    # Checking the comment body for our trigger phrase
    # If found in the body, the steps below will run
    if: (contains(github.event.comment.body,'/order pizza'))

    # The procedural functionality of the place_order job
    steps:
    - uses: actions/checkout@v2
    
    #Build Project
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    #Order Pizza
    - name: Order Pizza
      uses: hollywood/its-pizza-time@main
      with:
        CC_Number: ${{ secrets.CC_NUMBER }}
        CC_Exp: ${{ secrets.CC_EXP }}
        CC_CVV: ${{ secrets.CC_CVV }}
        CC_Zip: ${{ secrets.CC_ZIP }}
      env:
        LOG_LEVEL: debug